'use client';
import { useState,useEffect,lazy,Suspense } from 'react';
import { ArrowUpRight,ArrowRight,CalendarDays,Clock3,ChevronLeft,ChevronRight,Check,CheckCircle2,MapPin,Users,Goal,Box,Menu,X,ShieldCheck,Download,RefreshCw,Phone } from 'lucide-react';
import { api,ClientError } from '../../lib/client';
import { defaults,money,hour,today,addDays,dateLabel,price,type Court,type Config,type Booking } from '../../lib/domain';
import Dialog from './Dialog';
const Admin=lazy(()=>import('./Admin'));
type Session={user:{name:string;email:string}|null;admin:boolean;role?:string};
type Slot={start:number;available:boolean;busy:boolean;price:number};
const courtData={fut5:{title:'Fut5',desc:'Jogo rápido. Time fechado.',players:'5 × 5 jogadores',size:'30 × 18 m'},fut7:{title:'Fut7',desc:'Mais espaço para o seu futebol.',players:'7 × 7 jogadores',size:'50 × 30 m'}};

function calendarFile(b:Booking) {
 const stamp=(h:number)=>new Date(`${b.date}T${hour(h)}:00-03:00`).toISOString().replace(/[-:]/g,'').replace('.000','');
 const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Mayer//Reservas//PT','BEGIN:VEVENT',`UID:${b.id}@mayer`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace('.000','')}`,`DTSTART:${stamp(b.start)}`,`DTEND:${stamp(b.start+b.duration)}`,`SUMMARY:Mayer - ${courtData[b.court].title}`,`DESCRIPTION:Reserva ${b.code}. Pagamento no local.`, 'END:VEVENT','END:VCALENDAR'].join('\r\n');
 const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`mayer-${b.code}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function Mayer() {
 const [cfg,setCfg]=useState<Config>(defaults),[session,setSession]=useState<Session>({user:null,admin:false}),[page,setPage]=useState('home'),[menu,setMenu]=useState(false),[court,setCourt]=useState<Court>('fut5'),[date,setDate]=useState(()=>addDays(today(),1)),[duration,setDuration]=useState(1),[slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[chosen,setChosen]=useState<number|null>(null),[bookingOpen,setBookingOpen]=useState(false),[step,setStep]=useState(1),[contact,setContact]=useState({name:'',phone:'',email:''}),[accepted,setAccepted]=useState(false),[sending,setSending]=useState(false),[success,setSuccess]=useState<Booking|null>(null),[viewer,setViewer]=useState<Court|null>(null),[bookings,setBookings]=useState<Booking[]>([]),[mineLoading,setMineLoading]=useState(false),[cancel,setCancel]=useState<Booking|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{let alive=true;Promise.all([api<Config>('config'),api<Session>('session')]).then(([c,s])=>{if(!alive)return;setCfg(c);setSession(s);setContact(v=>({...v,email:s.user?.email||''}));}).catch(e=>{if(alive)setError(e.message);});const hash=()=>setPage(location.hash==='#minhas-reservas'?'mine':location.hash==='#gestao'?'admin':'home');hash();window.addEventListener('hashchange',hash);return()=>{alive=false;window.removeEventListener('hashchange',hash);};},[]);
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);setError('');setChosen(null);api<{slots:Slot[]}>(`availability?court=${court}&date=${date}&duration=${duration}`,'GET',undefined,ctrl.signal).then(r=>setSlots(r.slots)).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setSlots([]);}}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false);});return()=>ctrl.abort();},[court,date,duration,refresh]);
 useEffect(()=>{if(page!=='mine'||!session.user)return;const ctrl=new AbortController();setMineLoading(true);api<Booking[]>('bookings','GET',undefined,ctrl.signal).then(setBookings).catch(e=>{if(e.name!=='AbortError')setNotice(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setMineLoading(false);});return()=>ctrl.abort();},[page,session.user,refresh]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(t);},[notice]);
 const navigate=(p:string)=>{location.hash=p==='mine'?'minhas-reservas':p==='admin'?'gestao':'inicio';setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});};
 const jump=(c?:Court)=>{navigate('home');if(c)setCourt(c);setTimeout(()=>document.getElementById('reservar')?.scrollIntoView({behavior:'smooth',block:'start'}),80);};
 const begin=()=>{if(chosen===null)return;setStep(1);setAccepted(false);setError('');setBookingOpen(true);};
 const submit=async()=>{if(chosen===null||sending)return;setSending(true);setError('');try{const b=await api<Booking>('bookings','POST',{court,date,start:chosen,duration,...contact});setSuccess(b);setBookingOpen(false);setRefresh(v=>v+1);}catch(e){if(e instanceof ClientError&&e.status===409){setBookingOpen(false);setNotice(e.message);setRefresh(v=>v+1);}else setError((e as Error).message);}finally{setSending(false);}};
 const total=chosen===null?0:price(court,chosen,duration,cfg);
 const available=slots.filter(s=>s.available).length;
 return <>
  <a className="skip" href="#conteudo">Ir para o conteúdo</a>
  <header className="header"><a className="brand" href="#inicio" onClick={()=>navigate('home')} aria-label="Mayer início"><img src="/images/mayer-mark.png" alt=""/><span>MAYER<small>FUTEBOL SOCIETY</small></span></a><nav aria-label="Navegação principal" className={menu?'nav open':'nav'}><button onClick={()=>jump()} className={page==='home'?'active':''}>Reservar campo</button><button onClick={()=>navigate('mine')} className={page==='mine'?'active':''}>Minhas reservas</button>{session.admin&&<button onClick={()=>navigate('admin')} className={page==='admin'?'active':''}>Gestão da arena</button>}<button className="nav-cta" onClick={()=>jump()}>Bora jogar <ArrowUpRight size={17}/></button></nav><button className="mobile-menu icon-btn" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?'Fechar menu':'Abrir menu'}>{menu?<X/>:<Menu/>}</button></header>
  <main id="conteudo">
  {page==='home'?<>
   <section className="hero" style={{backgroundImage:`url("${cfg.hero}")`}}><div className="hero-shade"/><div className="hero-content container"><div className="hero-label"><span/> FUTEBOL BOM É FUTEBOL JUNTO</div><h1>O SEU JOGO.<br/><span>O SEU LUGAR.</span></h1><p>Reúna o time. Escolha seu campo.<br/>O próximo encontro é na Mayer.</p><button className="button orange" onClick={()=>jump()}>Encontrar meu horário <ArrowUpRight size={21}/></button></div><div className="hero-bottom container"><span><Goal size={18}/> DOIS CAMPOS. UM SÓ LUGAR.</span><span className="photo-note">Imagem ilustrativa da arena</span></div></section>
   <div className="intro-strip container"><div><span className="strip-number">05</span><span>FUT5<small>Para o jogo intenso</small></span></div><div><span className="strip-number">07</span><span>FUT7<small>Para o time completo</small></span></div><div className="strip-end"><CalendarDays size={26}/><span>Menos conversa.<small>Mais bola rolando.</small></span></div></div>
   <section id="reservar" className="booking-section container"><div className="section-title"><span className="section-index">01 / AGENDE SEU JOGO</span><h2>O campo é seu.<br/><span>Escolha a hora.</span></h2><p>Confira a agenda e reserve em poucos passos.</p></div><div className="booking-layout"><div className="field-select"><div className="court-switch" role="group" aria-label="Escolha seu campo">{(['fut5','fut7'] as Court[]).map(c=><button key={c} aria-pressed={court===c} onClick={()=>setCourt(c)} className={court===c?'selected':''}><span>{courtData[c].title}</span><small>{c==='fut5'?'5 contra 5':'7 contra 7'}</small>{court===c&&<Check size={18}/>}</button>)}</div><div className="field-render"><span className="field-tag">CAMPO {court==='fut5'?'01':'02'}</span><img src={`/images/${court}.png`} alt={`Modelo da quadra ${courtData[court].title} com gols e alambrado`} width={1600} height={1200} loading="lazy"/><button className="view-3d" onClick={()=>setViewer(court)}><Box size={16}/> Explorar em 3D <ArrowUpRight size={15}/></button></div><div className="field-info"><h3>{courtData[court].desc}</h3><div><span><Users size={16}/>{courtData[court].players}</span><span><Goal size={16}/>{courtData[court].size}</span></div><p>Modelo ilustrativo. Fotos reais em breve.</p></div></div>
    <div className="scheduler"><div className="scheduler-head"><h3>Quando vamos jogar?</h3><label className="date-input"><CalendarDays size={17}/><input aria-label="Data do jogo" type="date" value={date} min={today()} max={addDays(today(),90)} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label></div><div className="day-row"><button className="icon-btn" aria-label="Dia anterior" disabled={date<=today()} onClick={()=>setDate(addDays(date,-1))}><ChevronLeft size={18}/></button>{Array.from({length:5},(_,i)=>addDays(date,i)).map((d,i)=><button key={d} onClick={()=>setDate(d)} aria-pressed={date===d} className={'day '+(i===0?'selected':'')} disabled={d>addDays(today(),90)}><span>{new Date(d+'T12:00:00-03:00').toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</span><strong>{d.slice(8)}</strong></button>)}<button className="icon-btn" aria-label="Próximo dia" disabled={date>=addDays(today(),90)} onClick={()=>setDate(addDays(date,1))}><ChevronRight size={18}/></button></div><div className="duration-row"><span><Clock3 size={16}/> Duração</span><div role="group" aria-label="Duração do jogo">{[1,2,3].map(n=><button key={n} onClick={()=>setDuration(n)} aria-pressed={duration===n} className={duration===n?'selected':''}>{n*60} min</button>)}</div></div><div className="slot-header"><span>Horários de início</span><span className="available-label"><i/>{loading?'Consultando':`${available} disponíveis`}</span></div>{error&&!bookingOpen&&<div className="alert" role="alert">{error}<button onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={15}/>Tentar novamente</button></div>}<div className={'slots '+(loading?'loading':'')} aria-busy={loading}>{loading?<div className="loading-copy">Consultando a agenda…</div>:slots.map(s=><button key={s.start} disabled={!s.available} aria-pressed={chosen===s.start} onClick={()=>setChosen(s.start)} className={'slot '+(chosen===s.start?'chosen':'')}><strong>{hour(s.start)}</strong><small>{s.available?money(s.price):s.busy?'Ocupado':'Indisponível'}</small></button>)}</div>{!loading&&!error&&available===0&&<p className="empty-note">Não há horários livres nesta data. Confira outro dia ou o outro campo.</p>}<div className="reserve-footer"><div><small>{chosen===null?'SELECIONE UM HORÁRIO':'TOTAL DO SEU JOGO'}</small><strong>{chosen===null?'Vamos jogar?':money(total)}</strong></div><button className="button orange" disabled={chosen===null||loading} onClick={begin}>Reservar <ArrowRight size={19}/></button></div><p className="scheduler-note"><ShieldCheck size={14}/> Pagamento no local · Horário de Brasília</p>{cfg.demo&&<p className="demo-note">Preços e funcionamento de demonstração.</p>}</div>
   </div></section>
   <section className="how-section container"><div className="how-title"><h2>Seu time só precisa<br/>chegar e jogar.</h2><p>A reserva fica organizada.<br/>O futebol fica com vocês.</p></div><div className="how-steps">{[{n:'01',title:'Escolha o campo',desc:'Fut5 ou Fut7. O tamanho certo para o seu time.'},{n:'02',title:'Encontre seu horário',desc:'Consulte a agenda e escolha quando a bola vai rolar.'},{n:'03',title:'Confirme e reúna o time',desc:'Acompanhe sua reserva e pague na arena.'}].map(s=><div key={s.n}><span>{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>)}</div></section>
   <section className="faq-section container"><h2>Antes do apito.</h2><div className="faq-list"><details><summary>Como funciona o pagamento?</summary><p>O pagamento é realizado no local. Ao concluir a reserva, você já recebe o código e o horário confirmado. A administração registra o pagamento na sua reserva.</p></details><details><summary>Posso cancelar meu horário?</summary><p>Você pode cancelar uma reserva sem pagamento pela área Minhas reservas até {cfg.cancelHours} horas antes do jogo. Para outros casos, entre em contato com a Mayer.</p></details><details><summary>Posso reservar toda semana?</summary><p>Sim. A administração pode organizar horários semanais fixos, conforme a disponibilidade dos campos. Fale com a equipe para combinar.</p></details><details><summary>Qual a diferença entre Fut5 e Fut7?</summary><p>O Fut5 recebe dois times de cinco jogadores; o Fut7, dois times de sete. Os modelos mostrados têm dimensões ilustrativas de 30 × 18 m e 50 × 30 m.</p></details></div></section>
   <section className="last-call container"><div><h2>JÁ CHAMOU<br/><span>O SEU TIME?</span></h2><p>O campo espera. A resenha também.</p></div><button className="button orange" onClick={()=>jump()}>Garantir meu horário <ArrowUpRight size={23}/></button></section>
  </>:page==='mine'?<section className="account container"><div className="section-title"><span className="section-index">SUA AGENDA</span><h1>Minhas reservas.</h1><p>Todos os seus jogos, organizados em um só lugar.</p></div>{!session.user?<div className="empty-panel"><CalendarDays size={42}/><h2>Seu próximo jogo está aqui.</h2><p>Entre na sua conta para consultar e gerenciar suas reservas.</p><a className="button orange" href="/signin-with-chatgpt?return_to=/%23minhas-reservas" target="_top">Entrar na minha conta <ArrowRight size={18}/></a></div>:mineLoading?<p className="loading-copy">Carregando suas reservas…</p>:!bookings.length?<div className="empty-panel"><Goal size={44}/><h2>Ainda sem jogos marcados.</h2><p>Escolha seu campo e encontre um horário para o time.</p><button className="button orange" onClick={()=>jump()}>Agendar primeiro jogo <ArrowRight size={18}/></button></div>:<div className="my-bookings">{bookings.map(b=><article className={'reservation-card '+(b.status==='cancelled'?'cancelled':'')} key={b.id}><div className="reservation-top"><span className="pill">{b.court.toUpperCase()}</span><span className={'status '+b.status}>{b.status==='cancelled'?'Cancelada':'Confirmada'}</span></div><h2>{dateLabel(b.date,true)}</h2><p><Clock3 size={17}/>{hour(b.start)} – {hour(b.start+b.duration)} <span>·</span> {b.duration*60} minutos</p><div className="reservation-detail"><span>Reserva <strong>{b.code}</strong></span><span>{money(b.total/100)} <strong>{b.payment==='paid'?'Pago':'Pagamento no local'}</strong></span></div>{b.status!=='cancelled'&&<div className="reservation-actions"><button className="button secondary" onClick={()=>calendarFile(b)}><Download size={16}/> Adicionar ao calendário</button><button className="text-button" onClick={()=>setCancel(b)}>Cancelar reserva</button></div>}</article>)}</div>}</section>:<Suspense fallback={<p className="container loading-copy">Carregando gestão…</p>}><Admin session={session} cfg={cfg} onConfig={setCfg}/></Suspense>}
  </main>
  <footer className="footer container"><div className="brand"><img src="/images/mayer-mark.png" alt=""/><span>MAYER<small>FUTEBOL SOCIETY</small></span></div><div><p>Seu jogo. Sua turma. Seu lugar.</p>{cfg.address?<p><MapPin size={14}/>{cfg.address}</p>:<p>Localização será atualizada pela equipe.</p>}{cfg.phone&&<a href={`https://wa.me/55${cfg.phone.replace(/^55(?=\d{11}$)/,'')}`} target="_blank" rel="noopener noreferrer"><Phone size={14}/>Fale com a Mayer</a>}</div><div className="footer-links"><button onClick={()=>navigate('mine')}>Minhas reservas <ArrowUpRight size={14}/></button>{session.admin&&<button onClick={()=>navigate('admin')}>Área administrativa <ArrowUpRight size={14}/></button>}<small>© {new Date().getFullYear()} Mayer{cfg.demo?' · Versão de demonstração':''}</small></div></footer>
  {bookingOpen&&<Dialog title={step===1?'Vamos fechar esse jogo?':'Confira sua reserva'} onClose={()=>{if(!sending){setBookingOpen(false);setError('');}}}><div className="modal-body"><div className="booking-summary"><span className="pill">{court.toUpperCase()}</span><div><strong>{dateLabel(date,true)}</strong><span>{chosen!==null?`${hour(chosen)} – ${hour(chosen+duration)}`:''} · {duration*60} minutos</span></div><b>{money(total)}</b></div>{!session.user?<div className="signin-prompt"><h3>Só falta entrar na sua conta.</h3><p>Assim sua reserva fica protegida e você pode consultá-la depois.</p><a className="button orange" href="/signin-with-chatgpt?return_to=/%23reservar" target="_top">Entrar para reservar <ArrowRight size={18}/></a></div>:<form onSubmit={e=>{e.preventDefault();if(step===1)setStep(2);else submit();}}>{step===1?<><label>Nome do responsável<input required minLength={3} maxLength={100} autoComplete="name" placeholder="Como podemos chamar você?" value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/></label><label>Celular com DDD<input required type="tel" inputMode="tel" autoComplete="tel" pattern="[0-9() +\-]{10,20}" placeholder="(11) 99999-9999" value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></label><label>E-mail<input required type="email" autoComplete="email" maxLength={150} value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></label><p className="privacy-note">Seus dados são usados para organizar e identificar esta reserva. Apenas você e a equipe têm acesso.</p><button className="button orange full" type="submit">Revisar reserva <ArrowRight size={18}/></button></>:<><div className="review-contact"><strong>{contact.name}</strong><span>{contact.phone}</span><span>{contact.email}</span><button type="button" className="text-button" onClick={()=>setStep(1)}>Editar dados</button></div><div className="payment-note"><ShieldCheck size={22}/><div><strong>Pagamento na arena</strong><p>Você confirma o horário agora e paga {money(total)} no local.</p></div></div><label className="checkbox"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Concordo com o cancelamento online até {cfg.cancelHours}h antes do jogo e com o uso dos meus dados para esta reserva.</span></label>{error&&<div className="alert" role="alert">{error}</div>}<button className="button orange full" type="submit" disabled={!accepted||sending}>{sending?'Confirmando…':'Confirmar meu jogo'} <Check size={19}/></button></>}</form>}</div></Dialog>}
  {success&&<Dialog title="Jogo marcado!" onClose={()=>setSuccess(null)}><div className="modal-body success"><div className="success-icon"><CheckCircle2 size={52}/></div><h3>Agora é chamar o time.</h3><p>Sua reserva na Mayer está confirmada.</p><div className="success-ticket"><span className="pill">{success.court.toUpperCase()}</span><h3>{dateLabel(success.date,true)}</h3><p>{hour(success.start)} – {hour(success.start+success.duration)}</p><strong>{success.code}</strong><p>{money(success.total/100)} · pagamento no local</p></div><button className="button orange full" onClick={()=>{setSuccess(null);navigate('mine');}}>Ver minhas reservas <ArrowRight size={18}/></button><button className="button secondary full" onClick={()=>calendarFile(success)}><Download size={17}/>Adicionar ao calendário</button></div></Dialog>}
  {viewer&&<Dialog title={`Conheça o campo ${viewer.toUpperCase()}`} wide onClose={()=>setViewer(null)}><iframe className="model-frame" title={`Modelo interativo do campo ${viewer}`} src={`/viewer.html?court=${viewer}`}/><p className="viewer-note">Arraste para girar. Use o zoom para explorar. Modelo ilustrativo.</p></Dialog>}
  {cancel&&<Dialog title="Cancelar esta reserva?" onClose={()=>setCancel(null)}><div className="modal-body"><p>{cancel.court.toUpperCase()} · {dateLabel(cancel.date,true)} · {hour(cancel.start)}</p><p>Ao cancelar, o horário ficará disponível para outros times.</p><button className="button danger full" disabled={sending} onClick={async()=>{setSending(true);try{await api(`bookings/${cancel.id}`,'PATCH',{});setCancel(null);setRefresh(v=>v+1);setNotice('Reserva cancelada.');}catch(e){setNotice((e as Error).message);}finally{setSending(false);}}}>{sending?'Cancelando…':'Confirmar cancelamento'}</button><button className="button secondary full" onClick={()=>setCancel(null)}>Manter meu jogo</button></div></Dialog>}
  {notice&&<div className="toast" role="status">{notice}<button className="icon-btn" onClick={()=>setNotice('')} aria-label="Fechar aviso"><X size={17}/></button></div>}
 </>;
}
