import assert from 'node:assert/strict';
const origin=process.env.TEST_URL||'http://127.0.0.1:5173';
const login=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookie=login.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');
assert(cookie,'Local preview sign-in must provide a cookie');
const report=[];
async function req(path,method='GET',body,auth=true){const r=await fetch(origin+'/api/'+path,{method,headers:{...(auth?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json',Origin:origin}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};}
const c=(await req('config')).body,date=new Date(Date.now()+5*86400000).toISOString().slice(0,10),ids=[];
const base={court:'fut7',date,start:10,duration:2,name:'Teste automático Mayer',phone:'11999999999',email:'teste@example.com'};
try {
 assert.equal((await req('session')).body.admin,true);report.push('Owner-private admin bootstrap');
 assert.equal((await req('admin/bookings','GET',undefined,false)).status,401);
 assert.equal((await req('bookings','POST',base,false)).status,401);report.push('Anonymous writes and admin access rejected');
 const races=await Promise.all([req('bookings','POST',base),req('bookings','POST',base)]);
 assert.deepEqual(races.map(r=>r.status).sort(),[201,409]);const a=races.find(r=>r.status===201).body;ids.push(a.id);report.push('Concurrent booking: one accepted, one rejected');
 assert.equal(a.total,36000);
 let available=(await req(`availability?court=fut7&date=${date}&duration=1`)).body.slots;
 assert.equal(available.find(s=>s.start===10).available,false);assert.equal(available.find(s=>s.start===11).available,false);report.push('Full multi-hour interval unavailable');
 const before=(await req('bookings')).body.length;
 assert.equal((await req('admin/bookings','POST',{...base,start:9,duration:3})).status,409);
 assert.equal((await req('bookings')).body.length,before);report.push('Failed overlap rolls back booking and occupancy');
 const other=await req('bookings','POST',{...base,court:'fut5'});assert.equal(other.status,201);ids.push(other.body.id);report.push('Separate courts can share the same time');
 const occupied=await req('bookings','POST',{...base,start:14,duration:1});assert.equal(occupied.status,201);ids.push(occupied.body.id);
 assert.equal((await req(`admin/bookings/${a.id}`,'PATCH',{action:'reschedule',date,start:14})).status,409);
 available=(await req(`availability?court=fut7&date=${date}&duration=1`)).body.slots;
 assert.equal(available.find(s=>s.start===10).available,false);report.push('Failed reschedule preserves original reservation');
 assert.equal((await req(`admin/bookings/${a.id}`,'PATCH',{action:'reschedule',date,start:16})).status,200);
 available=(await req(`availability?court=fut7&date=${date}&duration=1`)).body.slots;
 assert.equal(available.find(s=>s.start===10).available,true);assert.equal(available.find(s=>s.start===16).available,false);report.push('Successful reschedule moves occupied interval');
 assert.equal((await req(`admin/bookings/${a.id}`,'PATCH',{action:'payment',paid:true})).status,200);
 assert.equal((await req(`bookings/${a.id}`,'PATCH',{})).status,400);report.push('Paid cancellation requires refund contact');
 assert.equal((await req(`admin/bookings/${a.id}`,'PATCH',{action:'payment',paid:false})).status,200);
 assert.equal((await req(`bookings/${a.id}`,'PATCH',{})).status,200);
 assert.equal((await req(`availability?court=fut7&date=${date}&duration=1`)).body.slots.find(s=>s.start===16).available,true);report.push('Cancellation releases availability');
 const recurring=await req('admin/bookings','POST',{...base,start:8,duration:1,weeks:4});assert.equal(recurring.status,201);
 const repeats=(await req('admin/bookings')).body.filter(b=>b.name===base.name&&b.start===8&&b.status==='confirmed');assert.equal(repeats.length,4);ids.push(...repeats.map(b=>b.id));report.push('Weekly recurring bookings created');
 assert.equal((await req('admin/bookings','POST',{...base,start:8,duration:1,weeks:4})).status,409);report.push('Recurring conflicts roll back the whole operation');
 const blocked=await req('admin/bookings','POST',{...base,court:'fut5',start:20,duration:1,kind:'blocked',name:'',phone:'',email:''});assert.equal(blocked.status,201);ids.push(blocked.body.id);
 assert.equal((await req(`availability?court=fut5&date=${date}&duration=1`)).body.slots.find(s=>s.start===20).available,false);report.push('Maintenance block hides slot');
 assert.equal((await req('bookings','POST',{...base,date:'2026-02-30'})).status,400);
 assert.equal((await req('bookings','POST',{...base,duration:-1})).status,400);
 assert.equal((await req('bookings','POST',{...base,phone:'123'})).status,400);
 assert.equal((await req('admin/config','PUT',{...c,days:[]})).status,400);report.push('Invalid dates, durations, contacts and settings rejected');
 const cross=await fetch(origin+'/api/bookings',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:'https://other.example'},body:JSON.stringify(base)});assert.equal(cross.status,403);report.push('Cross-origin write rejected');
 assert.equal((await req('admin/team','POST',{email:'equipe-teste@example.com',role:'staff'})).status,200);
 assert((await req('admin/team')).body.some(p=>p.email==='equipe-teste@example.com'&&p.role==='staff'));
 assert.equal((await req('admin/team','PATCH',{email:'equipe-teste@example.com'})).status,200);report.push('Team access invitation and removal');
 assert.equal((await req('admin/config','PUT',{...c,fut5:120.55})).status,200);
 const decimal=await req('bookings','POST',{...base,court:'fut5',start:12,duration:1});assert.equal(decimal.status,201);ids.push(decimal.body.id);assert.equal(decimal.body.total,12055);report.push('Prices are stored as integer cents');
 console.log(JSON.stringify({passed:report.length,checks:report},null,2));
} finally {await req('admin/config','PUT',c);await req('admin/team','PATCH',{email:'equipe-teste@example.com'});for(const id of [...new Set(ids)])await req(`admin/bookings/${id}`,'PATCH',{action:'cancel'});}
