import { useState } from 'react';
import { ArrowUpRight,ArrowRight,CalendarDays,Clock3,Users,Goal,Box,Menu,X,ShieldCheck } from 'lucide-react';
import Dialog from '../app/components/Dialog';
import type { Court } from '../lib/domain';

export const BOOKING_ORIGIN='https://mayer-futebol-society.ezkn-p1.chatgpt.site';
const asset=(path:string)=>import.meta.env.BASE_URL+path;
const data={fut5:{title:'Fut5',desc:'Jogo rápido. Time fechado.',players:'5 × 5 jogadores',size:'30 × 18 m'},fut7:{title:'Fut7',desc:'Mais espaço para o seu futebol.',players:'7 × 7 jogadores',size:'50 × 30 m'}};
export default function PagesLanding(){
 const [court,setCourt]=useState<Court>('fut5'),[menu,setMenu]=useState(false),[viewer,setViewer]=useState<Court|null>(null);
 const jump=()=>{setMenu(false);document.getElementById('campos')?.scrollIntoView({behavior:'smooth'});};
 return <>
 <a className="skip" href="#conteudo">Ir para o conteúdo</a>
 <header className="header"><a className="brand" href="#inicio" aria-label="Mayer início"><img src={asset('images/mayer-mark.png')} alt=""/><span>MAYER<small>FUTEBOL SOCIETY</small></span></a><nav aria-label="Navegação principal" className={menu?'nav open':'nav'}><button onClick={jump}>Nossos campos</button><a href={`${BOOKING_ORIGIN}/#minhas-reservas`}>Minhas reservas</a><a className="nav-cta" href={`${BOOKING_ORIGIN}/#reservar`}>Bora jogar <ArrowUpRight size={17}/></a></nav><button className="mobile-menu icon-btn" aria-expanded={menu} aria-label={menu?'Fechar menu':'Abrir menu'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="conteudo">
 <section id="inicio" className="hero" style={{backgroundImage:`url("${asset('images/mayer-arena.png')}")`}}><div className="hero-shade"/><div className="hero-content container"><div className="hero-label"><span/>FUTEBOL BOM É FUTEBOL JUNTO</div><h1>O SEU JOGO.<br/><span>O SEU LUGAR.</span></h1><p>Reúna o time. Escolha seu campo.<br/>O próximo encontro é na Mayer.</p><a className="button orange" href={`${BOOKING_ORIGIN}/#reservar`}>Encontrar meu horário <ArrowUpRight size={21}/></a></div><div className="hero-bottom container"><span><Goal size={18}/>DOIS CAMPOS. UM SÓ LUGAR.</span><span className="photo-note">Imagem ilustrativa da arena</span></div></section>
 <div className="intro-strip container"><div><span className="strip-number">05</span><span>FUT5<small>Para o jogo intenso</small></span></div><div><span className="strip-number">07</span><span>FUT7<small>Para o time completo</small></span></div><div className="strip-end"><CalendarDays size={26}/><span>Menos conversa.<small>Mais bola rolando.</small></span></div></div>
 <section id="campos" className="booking-section container"><div className="section-title"><span className="section-index">01 / CONHEÇA SEU CAMPO</span><h2>O campo é seu.<br/><span>Escolha o jogo.</span></h2><p>Fut5 ou Fut7. O tamanho certo para reunir seu time.</p></div><div className="booking-layout"><div className="field-select"><div className="court-switch" role="group" aria-label="Escolha seu campo">{(['fut5','fut7'] as Court[]).map(c=><button key={c} className={court===c?'selected':''} aria-pressed={court===c} onClick={()=>setCourt(c)}><span>{data[c].title}</span><small>{c==='fut5'?'5 contra 5':'7 contra 7'}</small></button>)}</div><div className="field-render"><span className="field-tag">CAMPO {court==='fut5'?'01':'02'}</span><img src={asset(`images/${court}.png`)} width={1600} height={1200} alt={`Modelo ilustrativo da quadra ${data[court].title} com gols e alambrado`} loading="lazy"/><button className="view-3d" onClick={()=>setViewer(court)}><Box size={16}/>Explorar em 3D <ArrowUpRight size={15}/></button></div><div className="field-info"><h3>{data[court].desc}</h3><div><span><Users size={16}/>{data[court].players}</span><span><Goal size={16}/>{data[court].size}</span></div><p>Dimensões e modelos ilustrativos. Fotos reais em breve.</p></div></div>
 <div className="scheduler pages-reserve"><div className="scheduler-head"><h3>Quando vamos jogar?</h3><CalendarDays size={21}/></div><p className="pages-reserve-intro">Acesse a agenda para consultar os horários reais e confirmar seu próximo jogo.</p><div className="pages-reserve-steps"><div><span>01</span><section><h4>Escolha a data</h4><p>Confira a disponibilidade do Fut5 ou Fut7.</p></section></div><div><span>02</span><section><h4>Encontre seu horário</h4><p>Reserve 60, 120 ou 180 minutos para seu time.</p></section></div><div><span>03</span><section><h4>Confirme sua reserva</h4><p>Acompanhe o jogo na sua conta e pague na arena.</p></section></div></div><a className="button orange full" href={`${BOOKING_ORIGIN}/#reservar`}>Abrir agenda de reservas <ArrowRight size={20}/></a><p className="scheduler-note"><ShieldCheck size={14}/>Sua reserva é confirmada na área de agendamento.</p><p className="pages-review-note">A agenda está em revisão privada e exige uma conta autorizada. Esta apresentação é pública.</p></div></div></section>
 <section className="how-section container"><div className="how-title"><h2>Seu time só precisa<br/>chegar e jogar.</h2><p>A reserva fica organizada.<br/>O futebol fica com vocês.</p></div><div className="how-steps">{[{n:'01',title:'Escolha o campo',desc:'Fut5 ou Fut7. O tamanho certo para o seu time.'},{n:'02',title:'Encontre seu horário',desc:'Consulte a agenda e escolha quando a bola vai rolar.'},{n:'03',title:'Confirme e reúna o time',desc:'Acompanhe sua reserva e pague na arena.'}].map(s=><div key={s.n}><span>{s.n}</span><h3>{s.title}</h3><p>{s.desc}</p></div>)}</div></section>
 <section className="faq-section container"><h2>Antes do apito.</h2><div className="faq-list"><details><summary>Como faço minha reserva?</summary><p>Use o botão Abrir agenda de reservas. Na área de agendamento, escolha campo, data e horário, entre na sua conta e confirme. A agenda está em revisão privada neste momento.</p></details><details><summary>Como funciona o pagamento?</summary><p>Esta versão utiliza pagamento no local. O valor e as regras aplicáveis aparecem na agenda antes da confirmação.</p></details><details><summary>Posso cancelar meu horário?</summary><p>Acesse Minhas reservas na área de agendamento. A política de cancelamento vigente é informada ao reservar.</p></details><details><summary>Posso reservar toda semana?</summary><p>A administração pode organizar horários semanais fixos, conforme a disponibilidade dos campos.</p></details><details><summary>Qual a diferença entre Fut5 e Fut7?</summary><p>O Fut5 recebe dois times de cinco jogadores; o Fut7, dois times de sete. Explore os modelos 3D para conhecer a proposta de cada campo.</p></details></div></section>
 <section className="last-call container"><div><h2>JÁ CHAMOU<br/><span>O SEU TIME?</span></h2><p>O campo espera. A resenha também.</p></div><a className="button orange" href={`${BOOKING_ORIGIN}/#reservar`}>Garantir meu horário <ArrowUpRight size={23}/></a></section>
 </main><footer className="footer container"><div className="brand"><img src={asset('images/mayer-mark.png')} alt=""/><span>MAYER<small>FUTEBOL SOCIETY</small></span></div><div><p>Seu jogo. Sua turma. Seu lugar.</p><p>Localização será atualizada pela equipe.</p></div><div className="footer-links"><a href={`${BOOKING_ORIGIN}/#minhas-reservas`}>Minhas reservas <ArrowUpRight size={14}/></a><a href={`${BOOKING_ORIGIN}/#gestao`}>Área administrativa <ArrowUpRight size={14}/></a><small>© {new Date().getFullYear()} Mayer · Apresentação de demonstração</small></div></footer>
 {viewer&&<Dialog title={`Conheça o campo ${viewer.toUpperCase()}`} wide onClose={()=>setViewer(null)}><iframe className="model-frame" title={`Modelo interativo do campo ${viewer}`} src={`${asset('viewer.html')}?court=${viewer}`}/><p className="viewer-note">Arraste para girar. Use o zoom para explorar. Modelo ilustrativo.</p></Dialog>}
 </>;
}
